server:
  port: 8081
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://0.0.0.0:3307/emlakdb"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: emlakburada-banner